// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const configuredUrl = import.meta.env.VITE_SUPABASE_URL;
const configuredPublishableKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(configuredUrl && configuredPublishableKey);

// Keep the public site available if deployment configuration is temporarily missing.
// Calls are guarded at their entry points while this fallback is active.
export const supabase = createClient<Database>(
  configuredUrl || 'https://configuration-required.supabase.co',
  configuredPublishableKey || 'configuration-required',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);